services:
  - type: worker
    name: telegram-renamer-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_ID
        value: 17709679
      - key: API_HASH
        value: faed0f05b5460e8dc9af32361421de1e
      - key: BOT_TOKEN
        value: 8429352817:AAERwEs5pMHyUm09VIXHx_xX2TyRgK2G43g
